/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;
import java.sql.*;
/**
 *
 * @author Veronika
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
   
 
    public Interface() {
        initComponents();
    clientButton.setOpaque(false);
    clientButton.setContentAreaFilled(false); //to make the content area transparent
    clientButton.setBorderPainted(false); //to make the borders transparent
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientImg = new javax.swing.JLabel();
        clientButton = new javax.swing.JButton();
        workerImg = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        workerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel database");
        setMinimumSize(new java.awt.Dimension(1300, 867));
        getContentPane().setLayout(null);

        clientImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/clientButton.png"))); // NOI18N
        clientImg.setText("jLabel3");
        getContentPane().add(clientImg);
        clientImg.setBounds(320, 490, 380, 130);

        clientButton.setBackground(new java.awt.Color(255, 255, 255));
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clientButton);
        clientButton.setBounds(360, 500, 290, 80);

        workerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/workerButton.png"))); // NOI18N
        workerImg.setText("jLabel2");
        getContentPane().add(workerImg);
        workerImg.setBounds(700, 480, 340, 130);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/reception.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1300, 867);

        workerButton.setText("jButton2");
        workerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(workerButton);
        workerButton.setBounds(720, 490, 300, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
       
        ClientForm clientForm = new ClientForm();
        clientForm.setVisible(true);
        this.hide();
    
        
        
        
    }//GEN-LAST:event_clientButtonActionPerformed

    private void workerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerButtonActionPerformed
        // TODO add your handling code here:
        WorkerForm workerForm = new WorkerForm();
        workerForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_workerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
                
                //connect to database
       
            }
                 
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton clientButton;
    private javax.swing.JLabel clientImg;
    private javax.swing.JButton workerButton;
    private javax.swing.JLabel workerImg;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

}
