/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author Veronika
 */
public class NewWorkerForm extends javax.swing.JFrame {
 private static final String USERNAME = "root";
    private static final String PASSWORD = "Axeldance1240";
   private static final String CONN_STRING = "jdbc:mysql://localhost:3306/mydbtest?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true";

    /**
     * Creates new form NewWorkerForm
     */
    public NewWorkerForm() {
        initComponents();
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderWorker = new javax.swing.JComboBox<>();
        textNameWorker = new javax.swing.JTextField();
        textPostWorker = new javax.swing.JComboBox<>();
        textDateWorker = new javax.swing.JTextField();
        textCountryWorker = new javax.swing.JTextField();
        textEmailWorker = new javax.swing.JTextField();
        textSalaryWorker = new javax.swing.JTextField();
        textPassWorker = new javax.swing.JTextField();
        textPhoneWorker = new javax.swing.JTextField();
        textSurnameWorker = new javax.swing.JTextField();
        textLoginWorker = new javax.swing.JTextField();
        textCityWorker = new javax.swing.JTextField();
        IDworker = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nextbuttWorker = new javax.swing.JButton();
        LogoutaddWorker = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 867));
        getContentPane().setLayout(null);

        genderWorker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(genderWorker);
        genderWorker.setBounds(760, 410, 150, 40);

        textNameWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(textNameWorker);
        textNameWorker.setBounds(330, 330, 150, 40);

        textPostWorker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Hotel Manager", "Assistant Hotel Manager", "Housekeeping Supervisor", "Front Desk Supervisor", "Supervisor of Guest Services", "Housekeeping" }));
        textPostWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPostWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(textPostWorker);
        textPostWorker.setBounds(330, 650, 150, 40);
        getContentPane().add(textDateWorker);
        textDateWorker.setBounds(330, 410, 150, 40);
        getContentPane().add(textCountryWorker);
        textCountryWorker.setBounds(330, 490, 150, 40);
        getContentPane().add(textEmailWorker);
        textEmailWorker.setBounds(330, 570, 150, 40);
        getContentPane().add(textSalaryWorker);
        textSalaryWorker.setBounds(760, 650, 150, 40);
        getContentPane().add(textPassWorker);
        textPassWorker.setBounds(1110, 410, 150, 40);
        getContentPane().add(textPhoneWorker);
        textPhoneWorker.setBounds(760, 490, 150, 40);
        getContentPane().add(textSurnameWorker);
        textSurnameWorker.setBounds(760, 330, 150, 40);
        getContentPane().add(textLoginWorker);
        textLoginWorker.setBounds(1110, 330, 150, 40);
        getContentPane().add(textCityWorker);
        textCityWorker.setBounds(760, 570, 150, 40);

        IDworker.setEditable(false);
        IDworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDworkerActionPerformed(evt);
            }
        });
        getContentPane().add(IDworker);
        IDworker.setBounds(330, 170, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/AddWorker.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 890);

        nextbuttWorker.setText("jButton1");
        nextbuttWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(nextbuttWorker);
        nextbuttWorker.setBounds(710, 730, 170, 40);

        LogoutaddWorker.setText("jButton2");
        LogoutaddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutaddWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutaddWorker);
        LogoutaddWorker.setBounds(1240, 60, 50, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(760, 650, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbuttWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttWorkerActionPerformed
     try {
         // TODO add your handling code here:
         //save to database
         sqlKey workersKey = new sqlKey();
         
         int id = workersKey.id_incrementable();
         
         if (new DBclass().add(id,textNameWorker.getText(),textSurnameWorker.getText(), Integer.parseInt(textDateWorker.getText()),textCountryWorker.getText(),textEmailWorker.getText(),textPostWorker.getSelectedItem().toString(),genderWorker.getSelectedItem().toString(),Integer.parseInt(textPhoneWorker.getText()),textCityWorker.getText(),Integer.parseInt(textSalaryWorker.getText()),textLoginWorker.getText(),textPassWorker.getText()))
         {
             WorkerPortail workerPortail = new WorkerPortail();
             workerPortail.setVisible(true);
             this.hide();
             System.out.println("Successfully Inserted");
         }else{
             System.out.println("Error");
         }
     } catch (SQLException ex) {
         Logger.getLogger(NewWorkerForm.class.getName()).log(Level.SEVERE, null, ex);
     }
       
    }//GEN-LAST:event_nextbuttWorkerActionPerformed

    private void LogoutaddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutaddWorkerActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutaddWorkerActionPerformed

    private void genderWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderWorkerActionPerformed
        // TODO add your handling code here:
        String[] gender = { "Male", "Female" };
    }//GEN-LAST:event_genderWorkerActionPerformed

    private void textNameWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameWorkerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textNameWorkerActionPerformed

    private void IDworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDworkerActionPerformed
        // TODO add your handling code here:       

    }//GEN-LAST:event_IDworkerActionPerformed

    private void textPostWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPostWorkerActionPerformed
        // TODO add your handling code here:
             String[] post = { "Administrator","Hotel Manager","Assistant Hotel Manager","Housekeeping Supervisor","Front Desk Supervisor","Supervisor of Guest Services","Housekeeping"};
    }//GEN-LAST:event_textPostWorkerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewWorkerForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDworker;
    private javax.swing.JButton LogoutaddWorker;
    private javax.swing.JComboBox<String> genderWorker;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextbuttWorker;
    private javax.swing.JTextField textCityWorker;
    private javax.swing.JTextField textCountryWorker;
    private javax.swing.JTextField textDateWorker;
    private javax.swing.JTextField textEmailWorker;
    private javax.swing.JTextField textLoginWorker;
    private javax.swing.JTextField textNameWorker;
    private javax.swing.JTextField textPassWorker;
    private javax.swing.JTextField textPhoneWorker;
    private javax.swing.JComboBox<String> textPostWorker;
    private javax.swing.JTextField textSalaryWorker;
    private javax.swing.JTextField textSurnameWorker;
    // End of variables declaration//GEN-END:variables
}
