/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;

/**
 *
 * @author Veronika
 */
public class RoomsForm extends javax.swing.JFrame {

    /**
     * Creates new form RoomsForm
     */
    public RoomsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        SearchRoom = new javax.swing.JPanel();
        backgroundSearchrRoom = new javax.swing.JLabel();
        LogoutSearchRoom = new javax.swing.JButton();
        HomeSearchRoom = new javax.swing.JButton();
        ViewAll = new javax.swing.JPanel();
        backgroundViewRoom = new javax.swing.JLabel();
        LogoutViewRoom = new javax.swing.JButton();
        HomeViewRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 867));

        SearchRoom.setLayout(null);

        backgroundSearchrRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/SearchRoom.png"))); // NOI18N
        SearchRoom.add(backgroundSearchrRoom);
        backgroundSearchrRoom.setBounds(0, 0, 1300, 867);

        LogoutSearchRoom.setText("jButton2");
        LogoutSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutSearchRoomActionPerformed(evt);
            }
        });
        SearchRoom.add(LogoutSearchRoom);
        LogoutSearchRoom.setBounds(1250, 50, 49, 49);

        HomeSearchRoom.setText("jButton1");
        HomeSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSearchRoomActionPerformed(evt);
            }
        });
        SearchRoom.add(HomeSearchRoom);
        HomeSearchRoom.setBounds(1194, 50, 40, 45);

        jTabbedPane1.addTab("Search Room", SearchRoom);

        ViewAll.setLayout(null);

        backgroundViewRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/ViewRoom.png"))); // NOI18N
        ViewAll.add(backgroundViewRoom);
        backgroundViewRoom.setBounds(0, 0, 1320, 867);

        LogoutViewRoom.setText("jButton3");
        LogoutViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutViewRoomActionPerformed(evt);
            }
        });
        ViewAll.add(LogoutViewRoom);
        LogoutViewRoom.setBounds(1250, 50, 40, 46);

        HomeViewRoom.setText("jButton1");
        HomeViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeViewRoomActionPerformed(evt);
            }
        });
        ViewAll.add(HomeViewRoom);
        HomeViewRoom.setBounds(1190, 50, 42, 42);

        jTabbedPane1.addTab("View all", ViewAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutSearchRoomActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutSearchRoomActionPerformed

    private void LogoutViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutViewRoomActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutViewRoomActionPerformed

    private void HomeSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSearchRoomActionPerformed
        // TODO add your handling code here:
         WorkerPortail workerPortail = new WorkerPortail();
        workerPortail.setVisible(true);
        this.hide();
    }//GEN-LAST:event_HomeSearchRoomActionPerformed

    private void HomeViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeViewRoomActionPerformed
        // TODO add your handling code here:
         WorkerPortail workerPortail = new WorkerPortail();
        workerPortail.setVisible(true);
        this.hide();
    }//GEN-LAST:event_HomeViewRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeSearchRoom;
    private javax.swing.JButton HomeViewRoom;
    private javax.swing.JButton LogoutSearchRoom;
    private javax.swing.JButton LogoutViewRoom;
    private javax.swing.JPanel SearchRoom;
    private javax.swing.JPanel ViewAll;
    private javax.swing.JLabel backgroundSearchrRoom;
    private javax.swing.JLabel backgroundViewRoom;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
