/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;

/**
 * @author Veronika
 */
public class WorkerPortail extends javax.swing.JFrame {

    /**
     * Creates new form WorkerPortail
     */
    public WorkerPortail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        roomsButton = new javax.swing.JButton();
        clientDetailsButton = new javax.swing.JButton();
        BreakfastButton = new javax.swing.JButton();
        ReportsButt = new javax.swing.JButton();
        WorkerDetailsButton = new javax.swing.JButton();
        SettingsButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 867));
        getContentPane().setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/workerPortailFinal.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -60, 1560, 980);

        LogoutButton.setText("jButton1");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(1150, 50, 130, 40);

        roomsButton.setText("jButton1");
        roomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(roomsButton);
        roomsButton.setBounds(960, 203, 210, 270);

        clientDetailsButton.setText("jButton1");
        clientDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clientDetailsButton);
        clientDetailsButton.setBounds(470, 200, 210, 280);

        BreakfastButton.setText("jButton2");
        BreakfastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreakfastButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BreakfastButton);
        BreakfastButton.setBounds(480, 543, 210, 270);

        ReportsButt.setText("jButton1");
        ReportsButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtActionPerformed(evt);
            }
        });
        getContentPane().add(ReportsButt);
        ReportsButt.setBounds(710, 543, 210, 270);

        WorkerDetailsButton.setText("jButton1");
        WorkerDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(WorkerDetailsButton);
        WorkerDetailsButton.setBounds(720, 200, 200, 270);

        SettingsButt.setText("jButton1");
        SettingsButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtActionPerformed(evt);
            }
        });
        getContentPane().add(SettingsButt);
        SettingsButt.setBounds(960, 543, 210, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();

    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void roomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsButtonActionPerformed
        // TODO add your handling code here:
        RoomsForm roomsForm = new RoomsForm();
        roomsForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_roomsButtonActionPerformed

    private void clientDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientDetailsButtonActionPerformed
        // TODO add your handling code here:
        ClientDetails clientDetails = new ClientDetails();
        clientDetails.setVisible(true);
        this.hide();
    }//GEN-LAST:event_clientDetailsButtonActionPerformed

    private void BreakfastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreakfastButtonActionPerformed
        // TODO add your handling code here:
        BreakfastForm breakfast = new BreakfastForm();
        breakfast.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BreakfastButtonActionPerformed

    private void ReportsButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtActionPerformed
        // TODO add your handling code here:
        ReportsForm reportsForm = new ReportsForm();
        reportsForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ReportsButtActionPerformed

    private void WorkerDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerDetailsButtonActionPerformed
        // TODO add your handling code here:
        WorkerDetailsForm workerDetailsForm = new WorkerDetailsForm();
        workerDetailsForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_WorkerDetailsButtonActionPerformed

    private void SettingsButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtActionPerformed
        // TODO add your handling code here:
        SettingsForm settingsForm = new SettingsForm();
        settingsForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_SettingsButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerPortail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerPortail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerPortail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerPortail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerPortail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BreakfastButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ReportsButt;
    private javax.swing.JButton SettingsButt;
    private javax.swing.JButton WorkerDetailsButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton clientDetailsButton;
    private javax.swing.JButton roomsButton;
    // End of variables declaration//GEN-END:variables
}
