/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;

import com.sun.istack.internal.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;

/**
 *
 * @author Veronika
 */
public class WorkerForm extends javax.swing.JFrame {
 private static final String USERNAME = "root";
    private static final String PASSWORD = "Axeldance1240";
   private static final String CONN_STRING = "jdbc:mysql://localhost:3306/mydbtest?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true";
    /**
     * Creates new form WorkerForm
     */
    public WorkerForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginErr = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        loginText = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        loginButtonW = new javax.swing.JButton();
        NewWorkerButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Worker");
        setMinimumSize(new java.awt.Dimension(1300, 867));
        getContentPane().setLayout(null);
        getContentPane().add(loginErr);
        loginErr.setBounds(550, 540, 210, 20);

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordText);
        passwordText.setBounds(550, 440, 210, 40);
        getContentPane().add(loginText);
        loginText.setBounds(550, 360, 210, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/workerForm.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1300, 870);

        backButton.setText("jButton1");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(13, 120, 70, 80);

        loginButtonW.setText("jButton2");
        loginButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonWActionPerformed(evt);
            }
        });
        getContentPane().add(loginButtonW);
        loginButtonW.setBounds(713, 653, 130, 40);

        NewWorkerButt.setText("jButton1");
        NewWorkerButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewWorkerButtActionPerformed(evt);
            }
        });
        getContentPane().add(NewWorkerButt);
        NewWorkerButt.setBounds(470, 650, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void loginButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonWActionPerformed
        // TODO add your handling code here:
         int flag = 1;
           try {
              
           Connection conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("Connected to database");
              Statement s = conn.createStatement();
              ResultSet rs = s.executeQuery("select * from mydbtest.workers");
              while (rs.next()){
              if ( rs.getString(12).equals(loginText.getText())&& rs.getString(13).equals(new String(passwordText.getPassword())) ){
                  
              flag = 0;
              break;
              }
              
              }
              if (flag == 0 ){
             WorkerPortail workerPortail = new WorkerPortail();
        workerPortail.setVisible(true);
        this.hide();
              }
              else {
               loginErr.setText("Invalid login/password");
              }
        } catch (SQLException e){
           
        }
        
        
        
      
   
    }//GEN-LAST:event_loginButtonWActionPerformed

    private void NewWorkerButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewWorkerButtActionPerformed
        // TODO add your handling code here:
        NewWorkerForm newWorkerForm = new NewWorkerForm();
        newWorkerForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_NewWorkerButtActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewWorkerButt;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton loginButtonW;
    private javax.swing.JLabel loginErr;
    private javax.swing.JTextField loginText;
    private javax.swing.JPasswordField passwordText;
    // End of variables declaration//GEN-END:variables
}
