/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinterface;

/**
 *
 * @author Veronika
 */
public class WorkerDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form WorkerDetailsForm
     */
    public WorkerDetailsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HomeSearchWorker = new javax.swing.JButton();
        LogoutSearchWorker = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomeSearchViewWorker = new javax.swing.JButton();
        LogoutViewWorker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/SearchWorker.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 830);

        HomeSearchWorker.setText("jButton1");
        HomeSearchWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSearchWorkerActionPerformed(evt);
            }
        });
        jPanel1.add(HomeSearchWorker);
        HomeSearchWorker.setBounds(1194, 30, 40, 50);

        LogoutSearchWorker.setText("jButton2");
        LogoutSearchWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutSearchWorkerActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutSearchWorker);
        LogoutSearchWorker.setBounds(1250, 30, 40, 50);

        jTabbedPane1.addTab("Search Worker", jPanel1);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseinterface/assets/ViewWorkers.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 830);

        HomeSearchViewWorker.setText("jButton1");
        HomeSearchViewWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSearchViewWorkerActionPerformed(evt);
            }
        });
        jPanel2.add(HomeSearchViewWorker);
        HomeSearchViewWorker.setBounds(1194, 30, 40, 50);

        LogoutViewWorker.setText("jButton2");
        LogoutViewWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutViewWorkerActionPerformed(evt);
            }
        });
        jPanel2.add(LogoutViewWorker);
        LogoutViewWorker.setBounds(1250, 30, 40, 50);

        jTabbedPane1.addTab("View Workers", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeSearchWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSearchWorkerActionPerformed
        // TODO add your handling code here:
        WorkerPortail workerPortail = new WorkerPortail();
        workerPortail.setVisible(true);
        this.hide();
    }//GEN-LAST:event_HomeSearchWorkerActionPerformed

    private void LogoutSearchWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutSearchWorkerActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutSearchWorkerActionPerformed

    private void HomeSearchViewWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSearchViewWorkerActionPerformed
        // TODO add your handling code here:
        WorkerPortail workerPortail = new WorkerPortail();
        workerPortail.setVisible(true);
        this.hide();
    }//GEN-LAST:event_HomeSearchViewWorkerActionPerformed

    private void LogoutViewWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutViewWorkerActionPerformed
        // TODO add your handling code here:
        Interface interFace = new Interface();
        interFace.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutViewWorkerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeSearchViewWorker;
    private javax.swing.JButton HomeSearchWorker;
    private javax.swing.JButton LogoutSearchWorker;
    private javax.swing.JButton LogoutViewWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
